### PR TITLE
Pso logging

### PR DESCRIPTION
**Pull request by reinthal**
add proper logging.

new files for each run. They get a relatively unique run number.

### CODE REVIEW

**Comment by rasake** [comment]
I get this printout when running main_optimization:

saving...
------ RESULTS -------
Best network
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
With relative mortality
10
Results have been saved to folder: ../best_network31398/fitnesses


How can the relative mortality be larger than 1?

**Comment by reinthal** [comment]
Dont know. I just printed the information I was handed. Thought it was weird also.

**Comment by reinthal** [comment]
if you follow the code the information comes from evaluate_weights @rasake

**Comment by rasake** [comment]
Yeah, it's not from this pull request anyway, so we might as well merge. I'll put it as a separate issue.

**Pull request merged**
